matrix:
  include:
    - os: osx
      # This version comes with oracle jdk8
      osx_image: xcode9.3
      language: java
      jdk:
        # Not all JDKs are supported on MacOS - https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks
        - oraclejdk8
      cache:
        directories:
          - $HOME/.m2
      # We don't need to cache artifacts generated during the build.
      before_cache:
        - rm -rf $HOME/.m2/repository/org/carlspring/strongbox
      before_install:
        - >
          mkdir -p $HOME/.m2;
          curl -o $HOME/.m2/settings.xml https://strongbox.github.io/assets/resources/maven/settings.xml;

    # Can't run on windows yet because of:
    #   https://travis-ci.community/t/windows-build-long-path-for-files/757
    #- os: windows
    #  language: shell

#
# This will be ran on all matrices.
#

git:
  depth: 1

# Skip default `install` step
install: true

# Build must produce logs or the VM will be terminated in 10 minutes.
before_script:
  - while sleep 120; do printf "[ %ss ] maven is still running...\n" `date +%H:%M:%S`; done &

script: mvn clean install -Dintegration.tests -T 2 -Daether.connector.resumeDownloads=false --log-file=build.log

after_failure:
  # Killing sleep loop
  - kill %1 2>&1
  - echo "Build has failed!"
  - cat build.log

after_success:
  # Killing sleep loop
  - kill %1 2>&1
  - echo "Build was successful!"
  - tail -n 500 build.log

